[package]
name = "weather-cli"
version = "0.1.0"
edition = "2021"
authors = ["Doruk Gurleyen <dorukgurleyen@gmail.com>"]

[[bin]]
name = "weather-cli"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11.9", features = ["json", "blocking"] }
serde = "1.0.136"
serde_json = "1.0.79"
